name: UnknownNetworkCore
version: "@version@"
api-version: 1.20
main: net.unknown.UnknownNetworkCorePlugin
softdepend: ["WorldGuard", "Multiverse-Core", "HolographicDisplays", "Vault", "Jecon", "BlueMap", "Votifier", "CoreProtect"]
permissions:
  unknown.core.default:
    default: true
    children:
      minecraft.command.skull: true
      unknown.core.command.skull: true
      minecraft.command.trash: true
      unknown.core.command.trash: true
      minecraft.command.reply: true
      unknown.core.command.reply: true
  unknown.core.admin:
    default: op
    children:
      minecraft.command.nick: true
      minecraft.command.skin: true
      minecraft.command.packet: true
      minecraft.command.setpose: true
      minecraft.command.eval: true
      minecraft.command.crash: true
      unknown.core.command.nick: true
      unknown.core.command.skin: true
      unknown.core.command.packet: true
      unknown.core.command.setpose: true
      unknown.core.command.eval: true
      unknown.core.command.crash: true
  unknown.survival.default:
    default: true
    children:
      minecraft.command.spawn: true
      minecraft.command.home: true
      minecraft.command.homes: true
      minecraft.command.sethome: true
      minecraft.command.delhome: true
      minecraft.command.tppet: true
      minecraft.command.fly: true
      minecraft.command.vote: true
      unknown.survival.command.spawn: true
      unknown.survival.command.home: true
      unknown.survival.command.homes: true
      unknown.survival.command.sethome: true
      unknown.survival.command.delhome: true
      unknown.survival.command.tppet: true
      unknown.survival.command.fly: true
      unknown.survival.command.vote: true
      unknown.survival.open_gui: true
  unknown.survival.admin:
    default: op
    children:
      minecraft.command.addhome: true
      minecraft.command.adelhome: true
      minecraft.command.ahome: true
      minecraft.command.ahomes: true
      minecraft.command.findhome: true
      minecraft.command.sethomecount: true
      unknown.survival.command.addhome: true
      unknown.survival.command.adelhome: true
      unknown.survival.command.ahome: true
      unknown.survival.command.ahomes: true
      unknown.survival.command.findhome: true
      unknown.survival.command.sethomecount: true
      unknown.survival.command.vote.manage: true
      unknown.survival.notify.mod: true