name: Pull Request Check

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "oracle"
          java-version: 21
          cache: "gradle"
      - name: Grant execution permission to gradlew
        run: chmod +x gradlew
      - name: Extract branch name for versioning
        id: extract_branch
        run: echo ::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})
      - name: Build
        env:
          BRANCH_NAME: ${{ steps.extract_branch.outputs.branch }}
        run: ./gradlew clean compileJava jar shadowJar reobfJar --info --profile
      - name: Set short SHA
        if: always()
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Save artifacts (for Paper)
        uses: actions/upload-artifact@v4
        with:
          name: UnknownNetworkCore-${{ env.short_sha }}.zip
          path: "build/libs/UnknownNetworkCore.jar"
      - name: Save artifacts (for Spigot)
        uses: actions/upload-artifact@v4
        with:
          name: UnknownNetworkCore-spigot-${{env.short_sha}}.zip
          path: "build/libs/UnknownNetworkCore-spigot.jar"
      - name: Upload gradle build profiling report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: UnknownNetworkCore_${{env.short_sha}}_build_report.zip
          path: "build/reports/profile/*"
      - name: Upload gradle build error report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: UnknownNetworkCore_${{env.short_sha}}_build_error_report.zip
          path: "build/reports/problems/*"